# Generated by Django 3.1.2 on 2021-07-06 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_auto_20210706_0235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='destription',
            new_name='description',
        ),
    ]
